#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

start_service() {
	[ "$(uci -q get mf832s.main.enabled 2>/dev/null)" = 1 ] || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/mf832s-monitor worker
	procd_set_param respawn 3600 5 5
	procd_close_instance
}
