#!/bin/sh

(
	case "$ACTION" in
		add|remove|register|unregister|move)
			signal=$(kill -l USR1 2>/dev/null)
			case "$signal" in
				''|*[!0-9]*) :;;
				*) ubus -t 1 call service signal "{\"name\":\"mf832s\",\"signal\":$signal}" >/dev/null 2>&1;;
			esac
			;;
	esac
	:
)
